version: "2"
services:
    apigateway:
        image: shahedk/apigateway:latest
        restart: always
        volumes:
          - "/home/shahedk/docker/data/apigateway/appsettings.json:/app/appsettings.json"
        ports:
          - "8090:80"
networks:
  default:
    external:
      name: elcnet
